spring:
  datasource:
    url: jdbc:h2:mem:socialnetwork
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 3600000 # 1 hora em milissegundos

server:
  port: 8080
